### ISSUE TITLE
API keys published

### ISSUE THREAD

**Issue by gabriuz** [lrtlt/mobile#1]
Hi,

is it okay to have API keys published publicly and ready to be indexed by search engines?
https://github.com/lrtlt/mobile/blob/1bfb2e4723e33af718b3d8edcd196b357505328e/android/app/google-services.json#L61

I think even though these keys can be extracted from the APK, it would make sense to add such files to `.gitignore`.

And thanks for publishing the code!

**Comment by damosevicius** [comment]
Hi,

Thank you for your finding. What's your suggestion how to solve it in the proper way ? By nature you can't build Android app without these credentials. We can create separate firebase project, but ...

**Comment by marius-jaskunas** [comment]
Google has a good documentation about how to secure API keys: https://developers.google.com/maps/api-key-best-practices

Environment variables could be one of the solutions.

**Comment by damosevicius** [comment]
Thank you all. We'll handle it.
