### ISSUE TITLE
Programele mi box priedelyje

### ISSUE THREAD

**Issue by lapius** [lrtlt/mobile#16]
**Is your feature request related to a problem? Please describe.**
Nera programeles android tv store. Ir siaip realiai isirasius apk faila, bandant pasileisti tiesiogine transliacija nuluzta appsas. 

**Describe the solution you'd like**
Butu gerai jei padarytumet versija televizoriui. Nes per mi box nera jokio lrt pasirinkimo.

**Describe alternatives you've considered**
Bandziau ieskoti gal yra koks ip ar budas pasileisti per plex media serveri. Deja irgi neradau nieko naudingo.

**Comment by lymatas** [comment]
Pritariu, labai pasigendu app'so Android TV platformai.

**Comment by baltad** [comment]
Iš savo įrenginio paieškokite Google store LRT programėlės Smart TV.
