### ISSUE TITLE
Missing loading indicator in "Naujausi" section

### ISSUE THREAD

**Issue by simnare** [lrtlt/mobile#2]
**Describe the bug**
There's no loading indicator in "Naujausi" section (probably in other sections as well). Loading indicator is only present in Home section

**To Reproduce**
1. Go to 'Home' section
2. Pull down to refresh
3. Go to 'Naujausi' section untill page is beeing refreshed
4. There's no indicator that content is being updated

**Expected behavior**
I would expect to see loading indicator in all sections

**Smartphone (please complete the following information):**
 - Device: Xiaomi Mi A2 lite
 - OS:Android 9

**Comment by KestasVenslauskas** [comment]
Will be fixed in upcoming release.
https://github.com/lrtlt/mobile/commit/9469209b9cc9df632aab4ebb9106e070f7e921e6
