### ISSUE TITLE
Missing README.md

### ISSUE THREAD

**Issue by SaltumDis** [lrtlt/mobile#3]
Project should have a README.md with installation and contribution guides. 
https://opensource.guide/starting-a-project/#writing-a-readme

**Comment by damosevicius** [comment]
Yes, I'll have it, just give us some time :)

**Comment by KestasVenslauskas** [comment]
Added short readme for now. https://github.com/lrtlt/mobile/commit/20dfdb587d43e0e13eaa6b6ae7516deb68ba9b95
