### ISSUE TITLE
Infogramas APP'se

### ISSUE THREAD

**Issue by zivile-gruzdiene** [lrtlt/mobile#55]
R.Stangytė skundžiasi, kad app'se blogai rodo infogramo įntarpus (Android, iOS).
Gal susijusi užduotis https://github.com/orgs/lrtlt/projects/7/views/1?pane=issue&itemId=67301742 (WebView issue (height bigger than 8000))

pvz NR.1. 
- WEB: https://www.lrt.lt/naujienos/pasaulyje/6/2318227/trumpo-saulys-buvo-registruotas-respublikonas-paaukojes-15-doleriu-demokratu-grupei
- APP: "Trumpo šaulys buvo registruotas respublikonas..."
-- infogramo intarpą "Trumpai" parodo
-- rodo tik pirmą intarpo punktą (Android, iOS)

Rodo app'se:
![Image](https://github.com/user-attachments/assets/c606617e-ac85-4d6e-be22-241de56bf2c7)

Turi būti:
![Image](https://github.com/user-attachments/assets/dbd6fcdd-edb7-459e-a388-c98a44556d16) 

Pvz NR.2:
- WEB: https://www.lrt.lt/naujienos/lrt-tyrimai/5/2206679/lrt-tyrimas-nacionalinio-stadiono-uzkulisiai-i-scena-zengia-avulis-bet-baltcap-toli-nesitraukia - didelis Infogramo paveikslėlis
- APP: "Nacionalinio stadiono užkulisiai...' 
-- nerodo visai intarpo, toje vietoje yra kelių eilučių tarpas

**Comment by zivile-gruzdiene** [comment]
Pvz.1 
APP: "Trumpo šaulys buvo registruotas respublikonas..."
- [ ] Infogramo embedas veikia 9Skyrelis "Svarbiausi faktai" app'se rodomas.
WEB'e: 
<div class="infogram-embed" data-id="32b86d0b-34b0-43bc-8dbe-715340f9f468" data-type="interactive" data-title="Trumpo išpuolis trumpai"></div><script>!function(e,n,i,s){var d="InfogramEmbeds";var o=e.getElementsByTagName(n)[0];if(window[d]&&window[d].initialized)window[d].process&&window[d].process();else if(!e.getElementById(i)){var r=e.createElement(n);r.async=1,r.id=i,r.src=s,o.parentNode.insertBefore(r,o)}}(document,"script","infogram-async","https://e.infogram.com/js/dist/embed-loader-min.js");</script>

**Comment by zivile-gruzdiene** [comment]
Pvz NR.2:
APP: "Nacionalinio stadiono užkulisiai...'
- [ ] nerodo visai intarpo, toje vietoje yra kelių eilučių tarpas
WEB: https://www.lrt.lt/naujienos/lrt-tyrimai/5/2206679/lrt-tyrimas-nacionalinio-stadiono-uzkulisiai-i-scena-zengia-avulis-bet-baltcap-toli-nesitraukia - didelis Infogramo paveikslėlis
Infogramo embed'as įkeltas kitaip, gal tai problema?
EMBED'as:
`<script id="infogram_0_11762041-20b2-44ce-90fa-868c17fca5d8" title="Pinigai stadionui" src=https://e.infogram.com/js/dist/embed.js?9Dq type="text/javascript"></script><!--googleon: all-->`

**Comment by zivile-gruzdiene** [comment]
@KestasVenslauskas 
tikrinau su Tesflight v 2.44.3 (107).
daugumoje vietų susitverkė Infogramo embedai (pvz.1), bet kai kur infogramo embedai įdėti kitaip ir jų app'se vis tiek nerodo (pvz.2).
Gal reikia susitarti, kaip įkelti embedus ir dėti taip, kad tiktų ir app'sui?

**Comment by KestasVenslauskas** [comment]
@zivile-gruzdiene Taip reiketu kelti inforgramas vienodai (taip kaip anksciau darete).
