### ISSUE TITLE
BUG'as: Tiesiogine transliacija. Audio/video switcheris

### ISSUE THREAD

**Issue by baltad** [lrtlt/mobile#59]
Tiesiogineje transliacijoje pasileidus LRT Radijas rodo viska su vaizdu. Pasirenki tik garsas - viskas ok. Pasirenki darkart su vaizdu - susidubliuoja garsas ir atsiranda tiesiogines transliacijos apacioje stickeris. 

https://github.com/user-attachments/assets/89e12f67-a09d-44d4-ae8a-c5ab4a393be5

**Comment by zivile-gruzdiene** [comment]
- Android v2.44.5 app'se atkartoju apačioje stickerį, bet man garsas nesusidubliuoja, stickeris garso lyg neturi
- iOS app v2.44.5(107) iš Testflight -  neatkartoju
