### ISSUE TITLE
TIESIOGIAI bloko atnaujinimas

### ISSUE THREAD

**Issue by baltad** [lrtlt/mobile#61]
APP'se reikia bloką TIESIOGIAI vaizduoti panašiai, kaip web versijoje
- [x] DUOMENYS apie kanalus bus iš to paties JSON'o. KANALŲ LOGO: @gincius 
- [x] App'se naujas blokas TIESIOGIAI vaizduojamas gerai
- [x] app'se bloke TIESIOGIAI lrt.lt tiesioginės transliacijos rodomos gerai
- [ ] Tamsioje temoje neišsiskiria kanalai, gal jiems reikia alternatyvių logotipų? @daumadauma @Noicom 

![Image](https://github.com/user-attachments/assets/fb542764-d8c7-40d6-97c7-5efe0de65097)

**Comment by daumadauma** [comment]
@KestasVenslauskas Ant logotipų vertikalios linijos reikia palikti kanalo akcentinę spalvą, o likusią logo dalį nudažyti baltai. Prisegu pvz. Ar atsiųst logotipus ar pats pasidarysi, nes turi turėt logo .svg fail'us?

<img width="647" alt="image" src="https://github.com/user-attachments/assets/33e650a8-03ac-446e-b136-31fefb81034a">

**Comment by KestasVenslauskas** [comment]
@daumadauma O dabar yra kitaip?
<img width="655" alt="image" src="https://github.com/user-attachments/assets/973830db-bce5-41fb-91f6-1b423a763957">

**Comment by daumadauma** [comment]
@KestasVenslauskas Nieko, viskas good
