### ISSUE TITLE
Subtitru problema

### ISSUE THREAD

**Issue by baltad** [lrtlt/mobile#73]
Ant iOS ne visi subtitrai gerai veikia.

Veikiantis subtitrai: https://www.lrt.lt/media/VIDEO/2024-11/ZIN43256_W_f871de8d-b076-4115-abb8-74dd925d4052.txt
Neveikiantis subtitrai: https://www.lrt.lt/media/VIDEO/2024-11/LAI90147_8a8b3d71-36a8-4bdb-9490-528ae870692a.txt

Vienintelis skirtumas tarp ju tai headeris

`WEBVTT - Generated by LKSSAIS`

Jeigu jo nera neveikia ant iOS subtitrai. Ar mes galime del to ka nors padaryti?

Problema pasidalinta su THEO komanda galbut jie tai isspres ir pas save.

**Comment by baltad** [comment]
Ats is THEO: Thank you for reaching out.

The “not working text track” is not a valid WebVTT, this is most likely why it is not working.

A WebVTT must start with a WEBVTT header on the file (like the working one).
You must use a decimal separator (a dot) on timings, so instead of 00:00:36,120, it should be 00:00:36.120.
Can you try correcting these as the first step and try?

**Comment by LinasBabrauskas** [comment]
Veikiantis - generuotas su "Ausim", o neveikiantis su kažkokia titravimo sistema pas televizininkus. Jau išėjo aiškintis ar galima paturbinti, kad atsirastų headeris ir kablelis pasikeistų į tašką.

**Comment by LinasBabrauskas** [comment]
https://www.lrt.lt/mediateka/irasas/2000375319/del-meiles-i-berlyna-persikelusi-migle-palyginus-su-vokieciais-esame-labai-atviri
Jau pataisė - tikrinkite

**Comment by KestasVenslauskas** [comment]
@LinasBabrauskas @baltad veikia 👍
